// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gRPCNet.Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CanPlayRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"transaction_id")]
        public int TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"concentrator_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ConcentratorId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"controller_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ControllerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"card_type")]
        public int CardType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"card_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"should_pay")]
        public bool ShouldPay { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"endpoint_rssi")]
        public int EndpointRssi { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"concentrator_rssi")]
        public int ConcentratorRssi { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CanPlayResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"response_code")]
        public int ResponseCode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"transaction_id")]
        public int TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"concentrator_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ConcentratorId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"controller_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ControllerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"card_type")]
        public int CardType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"card_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"card_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"service_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServiceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"service_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServiceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"permission")]
        public bool Permission { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"relay_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RelayType
        {
            get => __pbn__RelayType ?? "";
            set => __pbn__RelayType = value;
        }
        public bool ShouldSerializeRelayType() => __pbn__RelayType != null;
        public void ResetRelayType() => __pbn__RelayType = null;
        private string __pbn__RelayType;

        [global::ProtoBuf.ProtoMember(13, Name = @"relay_pulse")]
        public int RelayPulse
        {
            get => __pbn__RelayPulse.GetValueOrDefault();
            set => __pbn__RelayPulse = value;
        }
        public bool ShouldSerializeRelayPulse() => __pbn__RelayPulse != null;
        public void ResetRelayPulse() => __pbn__RelayPulse = null;
        private int? __pbn__RelayPulse;

        [global::ProtoBuf.ProtoMember(14, Name = @"relay_on_time")]
        public int RelayOnTime
        {
            get => __pbn__RelayOnTime.GetValueOrDefault();
            set => __pbn__RelayOnTime = value;
        }
        public bool ShouldSerializeRelayOnTime() => __pbn__RelayOnTime != null;
        public void ResetRelayOnTime() => __pbn__RelayOnTime = null;
        private int? __pbn__RelayOnTime;

        [global::ProtoBuf.ProtoMember(15, Name = @"relay_off_time")]
        public int RelayOffTime
        {
            get => __pbn__RelayOffTime.GetValueOrDefault();
            set => __pbn__RelayOffTime = value;
        }
        public bool ShouldSerializeRelayOffTime() => __pbn__RelayOffTime != null;
        public void ResetRelayOffTime() => __pbn__RelayOffTime = null;
        private int? __pbn__RelayOffTime;

        [global::ProtoBuf.ProtoMember(16, Name = @"relay_display_time")]
        public int RelayDisplayTime
        {
            get => __pbn__RelayDisplayTime.GetValueOrDefault();
            set => __pbn__RelayDisplayTime = value;
        }
        public bool ShouldSerializeRelayDisplayTime() => __pbn__RelayDisplayTime != null;
        public void ResetRelayDisplayTime() => __pbn__RelayDisplayTime = null;
        private int? __pbn__RelayDisplayTime;

        [global::ProtoBuf.ProtoMember(17, Name = @"display_line1")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DisplayLine1
        {
            get => __pbn__DisplayLine1 ?? "";
            set => __pbn__DisplayLine1 = value;
        }
        public bool ShouldSerializeDisplayLine1() => __pbn__DisplayLine1 != null;
        public void ResetDisplayLine1() => __pbn__DisplayLine1 = null;
        private string __pbn__DisplayLine1;

        [global::ProtoBuf.ProtoMember(18, Name = @"display_line2")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DisplayLine2
        {
            get => __pbn__DisplayLine2 ?? "";
            set => __pbn__DisplayLine2 = value;
        }
        public bool ShouldSerializeDisplayLine2() => __pbn__DisplayLine2 != null;
        public void ResetDisplayLine2() => __pbn__DisplayLine2 = null;
        private string __pbn__DisplayLine2;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServicePriceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"transaction_id")]
        public int TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"concentrator_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ConcentratorId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"controller_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ControllerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"card_type")]
        public int CardType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"card_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"service_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServiceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"endpoint_rssi")]
        public int EndpointRssi { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"concentrator_rssi")]
        public int ConcentratorRssi { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServicePriceResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"response_code")]
        public int ResponseCode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"transaction_id")]
        public int TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"concentrator_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ConcentratorId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"controller_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ControllerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"card_type")]
        public int CardType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"card_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"card_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"service_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServiceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"service_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ServiceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"price")]
        public double Price { get; set; }

    }

    //[global::System.ServiceModel.ServiceContract(Name = @"grpcnet.proto.CardService")]
    [global::ProtoBuf.Grpc.Configuration.Service(name: @"grpcnet.proto.CardService")]
    public interface ICardService
    {
        global::System.Threading.Tasks.ValueTask<CanPlayResponse> CanPlayAsync(CanPlayRequest value, global::ProtoBuf.Grpc.CallContext context = default);
        global::System.Threading.Tasks.ValueTask<ServicePriceResponse> ServicePriceAsync(ServicePriceRequest value, global::ProtoBuf.Grpc.CallContext context = default);
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
