// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gRPCNet.Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class KeepaliveResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.DateTime? Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Client { get; set; } = "";

    }

    //[global::System.ServiceModel.ServiceContract(Name = @"grpcnet.proto.KeepaliveService")]
    [global::ProtoBuf.Grpc.Configuration.Service(name: @"grpcnet.proto.KeepaliveService")]
    public interface IKeepaliveService
    {
        global::System.Collections.Generic.IAsyncEnumerable<KeepaliveResult> SubscribeAsync(global::ProtoBuf.Grpc.CallContext context = default);
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
